# .github/workflows/example.yml
name: Custom action Workflow

on:
  workflow_dispatch:

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Hello World Action
        uses: ./.github/actions/hello-world
        with:
          name: "Diego!"
