name: first workflow
on: 
  workflow_dispatch:
    inputs:
      runner:
        description: 'job runner'
        required: true
        type: choice
        options:
          - 'ubuntu-latest'
          - 'windows-latest'
jobs:
  build-artifact:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: get code
        uses: actions/checkout@v4
      - name: cache
        id: cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }} -dependencies-${{ hashFiles('**/package-lock.json') }}
          #path: ~\.npm
          path: node_modules
      - name: install dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: lint code
        run: npm run lint
      - name: build
        run: npm run build
      - name: upload biult artifact
        uses: actions/upload-artifact@v4
        with: 
          name: build_files
          path: dist
  if-failure:
    needs: build-artifact 
    runs-on: ${{ inputs.runner }}
    if: ${{ failure() }}
    steps:
      - name: echo failure
        run: echo "build failed"