# .github/workflows/follow_up.yml
name: Follow-up Workflow

on:
  workflow_call:
    inputs:
      message:
        description: "Message to display"
        required: true
        type: string

jobs:
  follow_up_job:
    runs-on: ubuntu-latest
    steps:
      - name: Display Follow-up Message
        run: echo "${{ inputs.message }}"
