name: Test Vulnerable GitHub Action

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  vulnerable-action-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v2

    # Example of a vulnerable action (hypothetical, replace with actual vulnerable version)
    - name: Use Vulnerable GitHub Action
      uses: vulnerable-org/vulnerable-action@v1.0.0
      with:
        input: example

    # Run Dependabot update simulation
    - name: Dependabot Dependency Management Test
      run: echo "Dependabot will suggest updates for dependencies."
